language: python
dist: xenial
sudo: true

python:
  - 3.9.1

install:
  - pip install -q -r requirements-dev.txt codecov

script:
  - flake8
  - pytest libpython --cov=libpython

after_success:
  - codecov

